### ISSUE TITLE
Local namespacing  @@ Infra:19:1

### ISSUE THREAD

**Issue by christopherreay** [Holochain/mapOnHolochain#182]
Decomposable localized namespacing to replace top-level domans and domain names. Names, words, and definitions can be locally collected and distributed through sharing and upvoting (or similar systems). My first name will be all my friends need to pull up my homepage, unless they know multiple people with the same first name, in which case they will be able to see the competing versions of where that string points in the system, and select their default or prioritized option (and optionally make visible their selection to influence the local taxonomy).

**Comment by andersaamodt** [comment]
Adding to background
