### ISSUE TITLE
Localized namespacing  @@ Infra:11:6

### ISSUE THREAD

**Issue by holochainTEAM** [Holochain/mapOnHolochain#303]
For URLs, usernames, and other usage of local nouns-as-names (proper names).
Features:
1. You will be known as your first name (or website short name) locally.
2. "Local" is defined by your local friends network.
3. You can go to the localized namespacing interface for any name reference and see the options for where that name can point, sorted by localized social network distance.
4. You can choose where the name will point for you, or differently weight the list so it will slant where it points more intelligently/customizably depending on context.

**Comment by andersaamodt** [comment]
Adding to background
